### ISSUE TITLE
Weird Behaviour

### ISSUE THREAD

**Issue by Emmo00** [lennyAiko/clacky#2]
when I try to run the scrip by passing all the flags on execution
```bash
node index.js --owner emmo00 --name learn-c --issue --closed --p 1 --pp 1
```
No info about the execution is returned.
![image](https://github.com/lennyAiko/git-orca/assets/88244468/938743f5-2289-4626-b7b2-eaa43a07753a)

This behavior is because, when we run it like this, the value of `argv.issue` is a boolean `true`, and not what is checked by the switch block ("issue"). this causes the switch to run the default code, which does not actually do anything (you probably forgot to add a output function to that string :D

**Comment by lennyAiko** [comment]
Ah I must have missed that, nice catch man!

**Comment by lennyAiko** [comment]
Thanks once again @Emmo00 , I have fixed the issue and I will close it now
